{% set version = "0.6.2" %}
{% set qdldlversion = "0.1.5" %}

package:
  name: libosqp
  version: {{ version }}

source:
  url: https://github.com/osqp/osqp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d973c33c3164caa381ed7387375347a46f7522523350a4e51989479b9d3b59c7
  patches:
    # see https://github.com/osqp/osqp/pull/310, can be dropped for osqp v1.0
    - patches/0001-Add-OSQP_RESPECT_BUILD_SHARED_LIBS-option.patch
    # use libqdldl from conda-forge
    - patches/0002-point-to-non-vendored-qdldl-headers.patch

build:
  number: 4
  run_exports:
    # No ABI policy is documented, let's be conservative
    - {{ pin_subpackage('libosqp', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libqdldl ={{ qdldlversion }}

test:
  commands:
    - test -f ${PREFIX}/include/osqp/osqp.h  # [not win]
    - test -f ${PREFIX}/lib/libosqp.so  # [linux]
    - test -f ${PREFIX}/lib/libosqp.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/osqp/osqp-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\osqp\\osqp.h (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\osqp.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\osqp.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\osqp\\osqp-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/osqp/osqp
  license: Apache-2.0
  summary: The Operator Splitting QP Solver.
  license_file:
    - osqp/LICENSE
    - qdldl/LICENSE
    - osqp/lin_sys/direct/qdldl/amd/LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
