{% set name = "libosqp" %}
{% set version = "0.6.2" %}
{% set qdldlversion = "0.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: osqp
    url: https://github.com/oxfordcontrol/osqp/archive/v{{ version }}.tar.gz
    sha256: d973c33c3164caa381ed7387375347a46f7522523350a4e51989479b9d3b59c7

  # Manually download repos that are used via git submodules
  # Note: make sure that the version used here is compatible with the one used in osqp
  - folder: qdldl
    url: https://github.com/oxfordcontrol/qdldl/archive/v{{ qdldlversion }}.tar.gz
    sha256: 2868b0e61b7424174e9adef3cb87478329f8ab2075211ef28fe477f29e0e5c99

build:
  number: 2
  run_exports:
    # No ABI policy is documented, let's be conservative
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                               # [not win]
    - cmake


test:
  commands:
    - test -f ${PREFIX}/include/osqp/osqp.h  # [not win]
    - test -f ${PREFIX}/lib/libosqp.so  # [linux]
    - test -f ${PREFIX}/lib/libosqp.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/osqp/osqp-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\osqp\\osqp.h (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\osqp.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\osqp.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\osqp\\osqp-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/oxfordcontrol/osqp
  license: Apache-2.0
  summary: The Operator Splitting QP Solver.
  license_file:
    - osqp/LICENSE
    - qdldl/LICENSE
    - osqp/lin_sys/direct/qdldl/amd/LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
