{% set name = "osqp" %}
{% set version = "1.0.0" %}

package:
  name: lib{{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dd6a1c2e7e921485697d5e7cdeeb043c712526c395b3700601f51d472a7d8e48

build:
  number: 1
  run_exports:
    # No ABI policy is documented, let's be conservative
    - {{ pin_subpackage('libosqp', max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msys2-git  # [win]
    - cmake
    - ninja-base
    # Needed to build UTs
    - python
    - numpy
    - scipy

test:
  commands:
    - test -f ${PREFIX}/include/osqp/osqp.h  # [not win]
    - test -f ${PREFIX}/lib/libosqp${SHLIB_EXT}  # [not win]
    - test ! -f ${PREFIX}/lib/libosqpstatic.a  # [not win]
    - test -f ${PREFIX}/lib/cmake/osqp/osqp-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\osqp\\osqp.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\osqp.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\osqp.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\osqp\\osqp-config.cmake exit 1  # [win]

about:
  home: https://osqp.org
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: The Operator Splitting QP Solver.
  description: |
    OSQP is a software package for solving convex quadratic programming (QP) problems. 
    It stands for "Operator Splitting Quadratic Program solver." OSQP is designed to 
    efficiently solve large-scale QP problems with sparsity structure.
  dev_url: https://github.com/osqp/osqp
  doc_url: https://osqp.org/docs/get_started

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
